# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc4e92c3fefa097e015971a81218f0333e40af778799b73c3e9354c577671cde26e3d401e016ace22352cabed2e9dbae85e76d99a9e59866f1c37fa6801e806

test:
  secret_key_base: 729a25f2c7e437fc906fad5c18e61605df18586713511acea18c17d9b619a5f97a0649063416b6f0836e3e257b1d083339eef3752a6b0761bbdaf52ea3c937d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
